version: "3"

networks:
  mongodb:
    external: true
  cutup:
    external: true

services:
  cutup:
    image: cutup:0.4.0
    build: .
    volumes:
      - "./config.yaml:/app/config.yaml:ro"
    networks:
      - mongodb
    ports:
      - 6001:6001
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: "1.50"
          memory: 384M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    stop_grace_period: 1s